/**
 * IPC payload types for the permission request/response flow between main and renderer.
 */
import { Plan } from '../../domain/models/Plan';

/** Channels used for permission-related IPC. */
export const PERMISSION_CHANNELS = {
  /** Main → Renderer: a high-risk plan needs user consent. */
  REQUEST: 'agent:permission-request',
  /** Renderer → Main: user decision for a permission request. */
  RESPONSE: 'agent:permission-response',
} as const;

/** Main → Renderer payload. */
export interface PermissionRequestPayload {
  /** Original voice text. */
  text: string;
  /** Plan generated by the agent. */
  plan: Plan;
  /** High-risk tools that require explicit consent. */
  tools: string[];
}

/** User decision for a permission request. */
export type PermissionDecision = 'deny' | 'allow-once' | 'allow-always';

/** Renderer → Main payload. */
export interface PermissionResponsePayload {
  /** Must match the tools sent in the request. */
  tools: string[];
  /** User decision. */
  decision: PermissionDecision;
}
